'use strict';

/**
 * Static achievement catalog describing automatic milestones exposed on the profile UI.
 * Definitions here align with achievementMilestones.js so the profile can display
 * friendly labels even when the database catalogue has not been seeded yet.
 */
module.exports = [
  {
    code: 'LEVEL_5',
    name: 'Tân binh cứng cáp',
    description: 'Đạt cấp 5 và mở khóa những lợi ích đầu tiên.',
    category: 'progression',
    icon: '',
    xpReward: 0,
  },
  {
    code: 'LEVEL_10',
    name: 'Chiến binh kỳ cựu',
    description: 'Tiếp tục luyện tập để chạm tới cấp 10.',
    category: 'progression',
    icon: '',
    xpReward: 0,
  },
  {
    code: 'LEVEL_20',
    name: 'Huyền thoại 4FUN',
    description: 'Cán mốc cấp 20 và trở thành biểu tượng của sòng bạc.',
    category: 'progression',
    icon: '',
    xpReward: 0,
  },
  {
    code: 'COINFLIP_ROOKIE',
    name: 'Coinflip Rookie',
    description: 'Làm quen với Coinflip bằng cách chơi 200 ván.',
    category: 'coinflip',
    icon: '',
    xpReward: 0,
  },
  {
    code: 'COINFLIP_VETERAN',
    name: 'Coinflip Veteran',
    description: 'Chinh phục 500 ván Coinflip.',
    category: 'coinflip',
    icon: '',
    xpReward: 0,
  },
  {
    code: 'COINFLIP_LEGEND',
    name: 'Coinflip Legend',
    description: 'Chơi 1.000 ván Coinflip để nhận huy hiệu tối thượng.',
    category: 'coinflip',
    icon: '',
    xpReward: 0,
    badgeUnlock: 'THE_FLIPPER',
  },
  {
    code: 'COINFLIP_CHAMPION',
    name: 'Coinflip Champion',
    description: 'Giành chiến thắng 250 ván Coinflip.',
    category: 'coinflip',
    icon: '',
    xpReward: 0,
  },
  {
    code: 'COINFLIP_CONQUEROR',
    name: 'Coinflip Conqueror',
    description: 'Chiến thắng 750 ván Coinflip và chứng tỏ đẳng cấp đỉnh cao.',
    category: 'coinflip',
    icon: '',
    xpReward: 0,
    badgeUnlock: 'LUCKY_STREAK',
  },
  {
    code: 'CHECKIN_STARTER',
    name: 'Thói quen mới',
    description: 'Nhận thưởng đăng nhập 7 ngày.',
    category: 'daily',
    icon: '',
    xpReward: 0,
  },
  {
    code: 'CHECKIN_VETERAN',
    name: 'Nghiện check-in',
    description: 'Kiên trì nhận thưởng đăng nhập 30 ngày.',
    category: 'daily',
    icon: '',
    xpReward: 0,
    badgeUnlock: 'LOYAL_VISITOR',
  },
  {
    code: 'REWARD_HUNTER',
    name: 'Thợ săn quà',
    description: 'Nhận thưởng hằng ngày 30 lần.',
    category: 'rewards',
    icon: '',
    xpReward: 0,
  },
  {
    code: 'REWARD_COLLECTOR',
    name: 'Nhà sưu tầm phần thưởng',
    description: 'Thu thập thưởng hằng ngày 100 lần.',
    category: 'rewards',
    icon: '',
    xpReward: 0,
    badgeUnlock: 'TREASURE_HUNTER',
  },
  {
    code: 'SOCIAL_STARTER',
    name: 'Kết nối đầu tiên',
    description: 'Kết bạn thành công với 5 người chơi.',
    category: 'social',
    icon: '',
    xpReward: 0,
  },
  {
    code: 'SOCIAL_BUTTERFLY',
    name: 'Mạng lưới 4FUN',
    description: 'Kết bạn thành công với 25 người chơi.',
    category: 'social',
    icon: '',
    xpReward: 0,
    badgeUnlock: 'SOCIAL_STAR',
  },
];
