// server/config/achievementMilestones.js
// Central definition list for achievements of different types.

module.exports = [
  {
    code: 'LEVEL_5',
    type: 'level',
    level: 5,
    title: 'Tân binh cứng cáp',
    message: 'Bạn đã đạt cấp 5! Thành tựu mới vừa được mở khóa.',
  link: '/collections',
    rewardBadge: 'LEVEL_5_BADGE',
  },
  {
    code: 'LEVEL_10',
    type: 'level',
    level: 10,
    title: 'Chiến binh kỳ cựu',
    message: 'Xin chúc mừng! Bạn đã đạt cấp 10 và mở khóa thêm một thành tựu.',
  link: '/collections',
    rewardBadge: 'LEVEL_10_BADGE',
  },
  {
    code: 'LEVEL_20',
    type: 'level',
    level: 20,
    title: 'Huyền thoại 4FUN',
    message: 'Đỉnh cao! Cấp 20 đã đạt, bạn là huyền thoại của CASI4F.',
  link: '/collections',
    rewardBadge: 'LEVEL_20_BADGE',
  },
  {
    code: 'COINFLIP_ROOKIE',
    type: 'counter',
    counter: 'coinflip.played',
    threshold: 200,
    title: 'Coinflip Rookie',
    message: 'Khởi động tuyệt vời! Bạn đã chơi 200 ván Coinflip.',
    link: '/history',
  },
  {
    code: 'COINFLIP_VETERAN',
    type: 'counter',
    counter: 'coinflip.played',
    threshold: 500,
    title: 'Coinflip Veteran',
    message: 'Cả đống kèo tung-xỉu! Bạn đã cán mốc 500 ván Coinflip.',
    link: '/history',
  },
  {
    code: 'COINFLIP_LEGEND',
    type: 'counter',
    counter: 'coinflip.played',
    threshold: 1000,
    title: 'Coinflip Legend',
    message: '1.000 ván Coinflip! Bạn xứng đáng với danh hiệu bậc thầy.',
    link: '/history',
    rewardBadge: 'THE_FLIPPER',
  },
  {
    code: 'COINFLIP_CHAMPION',
    type: 'counter',
    counter: 'coinflip.wins',
    threshold: 250,
    title: 'Coinflip Champion',
    message: 'Chuỗi thắng ấn tượng! Bạn đã thắng 250 ván Coinflip.',
    link: '/history',
  },
  {
    code: 'COINFLIP_CONQUEROR',
    type: 'counter',
    counter: 'coinflip.wins',
    threshold: 750,
    title: 'Coinflip Conqueror',
    message: 'Đỉnh cao phong độ! Bạn đã thắng 750 ván Coinflip.',
    link: '/history',
    rewardBadge: 'LUCKY_STREAK',
  },
  {
    code: 'CHECKIN_STARTER',
    type: 'counter',
    counter: 'checkin.days',
    threshold: 7,
    title: 'Thói quen mới',
    message: 'Bạn đã nhận thưởng đăng nhập tổng cộng 7 ngày.',
    link: '/rewards',
  },
  {
    code: 'CHECKIN_VETERAN',
    type: 'counter',
    counter: 'checkin.days',
    threshold: 30,
    title: 'Nghiện check-in',
    message: 'Bạn đã nhận thưởng đăng nhập tổng cộng 30 ngày.',
    link: '/rewards',
    rewardBadge: 'LOYAL_VISITOR',
  },
  {
    code: 'REWARD_HUNTER',
    type: 'counter',
    counter: 'rewards.daily.claimed',
    threshold: 30,
    title: 'Thợ săn quà',
    message: 'Bạn đã nhận thưởng hằng ngày tổng cộng 30 lần.',
    link: '/rewards',
  },
  {
    code: 'REWARD_COLLECTOR',
    type: 'counter',
    counter: 'rewards.daily.claimed',
    threshold: 100,
    title: 'Nhà sưu tầm phần thưởng',
    message: 'Bạn đã nhận thưởng hằng ngày tổng cộng 100 lần.',
    link: '/rewards',
    rewardBadge: 'TREASURE_HUNTER',
  },
  {
    code: 'SOCIAL_STARTER',
    type: 'counter',
    counter: 'social.friends.accepted',
    threshold: 5,
    title: 'Kết nối đầu tiên',
    message: 'Bạn đã kết bạn thành công với 5 người chơi.',
    link: '/friends',
  },
  {
    code: 'SOCIAL_BUTTERFLY',
    type: 'counter',
    counter: 'social.friends.accepted',
    threshold: 25,
    title: 'Mạng lưới 4FUN',
    message: 'Bạn đã kết bạn thành công với 25 người chơi.',
    link: '/friends',
    rewardBadge: 'SOCIAL_STAR',
  },
]
